
--1. Total Revenue generated by male and female customers
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
--2. customers used a discount but still spent more than the average
select customer_id , purchase_amount
from customer
where discount_applied ='Yes' and purchase_amount >= (select AVG(purchase_amount)from customer)
--3. top 5 products with the highest average review rating
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;
--4. Average purchase amounts between Standard and Express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
--5. Seeing whether subscribed customers spend more and comparing average spending and total revenue
--between subscribers and non subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spending,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by customer.subscription_status
order by total_revenue, avg_spending desc;
--6. 5 products that have the highest percentage of purchases with discounts applied.
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
